# ----------------------------------------------------------------------------#
#                                                                             #
#                              Battleship config                              #
#                                                                             #
# ----------------------------------------------------------------------------#

# name of the language file (in the folder 'language')
#   the default.yml file is overwriten on every server restart!
#   This means you will have to use the other files to customize the messages, but since i am adding messages regulary in updates
#   you can use the default file if you just want to have the up to date english default messages
langFile: "default.yml"



# number of ships in the game (only 1 or 2)

# size: 5 blocks
aircraftCarrier: 1
# size: 4 blocks
battleship: 1
# size: 3 blocks
cruiser: 2
# size: 2 blocks
destroyer: 1


gameBox:
  mainButton:
    # define the Material and data for the button (format: 'material:data')
    materialData: "EMERALD"
    # display name of the button
    displayName: "&3GemCrush"
    # lore of the button
    lore:
    - ""
    - "&1It's raining gems..."
  gameButtons:
    normalGame:
      materialData: "EMERALD"
      displayName: "&1It's raining gems"
      lore:
      - ""
      - "&4Moves: &220"
      - '&4Gems: &28'
      - '&4Bombs: &2true'
      - '&4Cost: &45'
      moves: 20
      # number of different gems in a normal game
      #   This number HAS TO BE equal or smaller then the number of gems defined in the section normalGems below
      #   8 or 7 are good numbers. 7 is easier and the game has to shuffle less but 8 is a bit more challenging
      differentGems: 8
      # enable/disable bombs for this game
      bombs: true
      # slot of the button in the gui
      #   be careful to not use the same twice ;)
      slot: 0
      cost: 5
    lessMovesAndLessGemTypes:
      materialData: "nether_star"
      displayName: "&1So much &l&epling"
      lore:
      - ""
      - "&4Moves: &210"
      - '&4Gems: &24'
      - '&4Bombs: &2true'
      - '&4Cost: &410'
      moves: 10
      differentGems: 4
      bombs: true
      slot: 5
      cost: 10
    materialdatatest:
      materialData: "nether_star"
      displayName: "&1The cheaper &l&epling"
      lore:
      - ""
      - "&4Moves: &210"
      - '&4Gems: &24'
      - '&4Bombs: &4false'
      - '&4Cost: &45'
      moves: 10
      differentGems: 4
      bombs: false
      slot: 6
      cost: 5







gameRules:
  # if this is true players can shoot again after a hit and the grids will change after every miss
  #   if it is false the grid will change after every shot regardless of hit/miss
  fireAgainAfterHit: true
  # false: the player whose fire timer ran out will loose the game
  # true: If a fire timer runs out it's the other players turn
  switchAttackerAfterFireTimerRanOut: false
  # play sounds in the game
  playSounds: true

# some stuff you can do when a game ends.
onGameEnd:
  # You can dispatch commands. Use %winner% for the playername of the winner and %loser% for the loser
  dispatchCommands:
    enabled: false
    commands:
    - "give %winner% diamond 1"
    - "tell %winner% congrats!"
    - "tell %loser% next time you'll beat him!"
  # You can broadcast. Use %winner% for the playername of the winner and %loser% for the loser
  broadcast:
    enabled: false
    messages:
    - "%winner% won against %loser% in a game of Battleship!"
    - "Do &2/bs %winner% &rto try against %winner% yourself ;)"     


# requires vault and an economy plugin
economy:
  enabled: false
  # both players pay
  cost: 0
  # winner gets
  reward: 0

# use "Material:data" or "ID:data"
# Some materials can not be displayed in an inventory, just test everything after changing
# You are advised to use different materials. At least on the same grid
#   otherwise the game could break
materials:
  yourGrid:
    ship:
      material: "Iron_block"
      name: "&7Ship"
    lockedShip:
      material: "7"
      name: "&8Locked ship"
    miss:
      material: "160:3"
      name: "&2Yeah! A miss!"
    hit:
      material: "35:14"
      name: "&4Damn! A hit..."
    water:
      material: "160:11"
      name: "&1Water"
  othersGrid:
    cover:
      material: "WOOL:7"
      name: "&6Cover"
    miss:
      material: "160:11"
      name: "&4That did not hit..."
    hit:
      material: "Iron_block"
      name: "&2Booom! Gotcha"

    
# Customise the timers used in the game (all times in seconds)
timers:
  # timer used during the ship-set part of the game
  shipSetTimer:
    countdown: 30
  # timer used during the main part of the game
  fireTimer:
    countdown: 10
  # timer used when attacker and defender change
  changingGrids:
    countdown: 3
  # timer used for the invitations
  invitationTimer:
    validFor: 15